"""Add payment_id and paid_at fields to Order

Revision ID: 429b5faebf9f
Revises: cdf431543126
Create Date: 2026-03-03 00:18:49.756860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '429b5faebf9f'
down_revision: Union[str, Sequence[str], None] = 'cdf431543126'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('payment_id', sa.String(length=64), nullable=True))
    op.add_column('orders', sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True))
    op.create_unique_constraint(None, 'orders', ['payment_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='unique')
    op.drop_column('orders', 'paid_at')
    op.drop_column('orders', 'payment_id')
    # ### end Alembic commands ###
